# Generated by Django 4.2.10 on 2024-02-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_auther_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excrept',
            new_name='excerpt',
        ),
    ]
